# Linear Regression for _ multi variate(with multiple independent features

### Example-1 Predict Home prices

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [7]:
df=pd.read_csv('homeprices.csv')

In [8]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
import math # to make median integer use math function
median_bedroom=math.floor(df.bedrooms.median())
median_bedroom

4

In [10]:
df.bedrooms=df.bedrooms.fillna(median_bedroom)
df # Datapoint replaced with median

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
lin_reg=linear_model.LinearRegression()
lin_reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [12]:
m=[[4500,6,8]]
prediction_value_In_Rs=lin_reg.predict(m)
prediction_value_In_Rs

C:\Users\APL73176-NITESHKUMAR\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([840083.52780358])

In [13]:
x_=lin_reg.coef_
x_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
b_=lin_reg.intercept_
b_

221323.00186540408

In [15]:
#By using m*x+b equation

result=0

for i in range(len(m[0])):
    result+=m[0][i]*x_[i]
result+=b_

result

840083.5278035813

### Example-2 Predict Hiring Salary

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [17]:
df=pd.read_csv('hiring.csv')

In [18]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [20]:
!pip install word2number

In [21]:
from word2number import w2n # Convert text number to numerical number

In [22]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [23]:
import math
mean_test_score = math.floor(df['test_score(out of 10)'].median())
mean_test_score

8

In [24]:
import math
mean_test_score = math.floor(df['test_score(out of 10)'].mean())
mean_test_score

7

In [25]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [26]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [27]:
m=[[11,10,10]]
predicted_salary=lin_reg.predict(m)
predicted_salary

C:\Users\APL73176-NITESHKUMAR\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([424127.31041983])

### Save model to file to use it whenever required (Using Pickle)

In [1]:
import pickle

In [39]:
with open ('model_pickle','wb') as f:
    pickle.dump (reg,f) # reg is linear regression file in previous line
#This model_pickle file is like brain 
# i can share this to anyone to use without wirting any further model 
#they can use this model to run the similar dattaset 

In [36]:
with open('model_pickle', 'rb') as f:
    regrees = pickle.load(f)

In [40]:
regrees.predict([[15,15,15]])

C:\Users\APL73176-NITESHKUMAR\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([124358.56166135])

### Save model to file to use it whenever required (Using Joblib)

In [54]:
!pip install --upgrade scikit-learn

In [56]:
!pip install joblib

In [59]:
import joblib

In [61]:
with open ('model_joblib','wb') as f:
    joblib.dump (reg,f) 

In [62]:
with open('model_joblib', 'rb') as f:
    regrees = joblib.load(f)

regrees.predict([[15,15,15]])

C:\Users\APL73176-NITESHKUMAR\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([124358.56166135])